## PostgreSQL admin user
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
postgresqlUsername: postgres

## PostgreSQL password
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
##
postgresqlPassword: pg

## PostgreSQL password using existing secret
## existingSecret: secret

## Create a database
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run
##
postgresqlDatabase: sfdata

initdbScripts:
  db-init.sql: |
    CREATE TABLE tweets (
    id serial PRIMARY KEY,
    text text,
    language text,
    source text,
    datetime text DEFAULT now()
    );
    CREATE TABLE counts (
    language text PRIMARY KEY,
    count integer
    );


