auth:
  postgresPassword: pg
  database: sfdata
primary:
  initdb:
    scripts:
      db-init.sql: |
        CREATE TABLE tweets (
        id serial PRIMARY KEY,
        text text,
        language text,
        source text,
        datetime text DEFAULT now()
        );
        CREATE TABLE counts (
        language text PRIMARY KEY,
        count integer
        );