datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: prometheus
     type: prometheus
     url: http://prometheus-server
     access: proxy
     isDefault: true
   - name: postgres
     type: postgres
     url: pg-postgresql:5432
     database: sfdata
     user: postgres
     secureJsonData:
      password: pg
     jsonData:
       sslmode: disable
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    custom-dashboard:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "target": {
                  "limit": 100,
                  "matchAny": false,
                  "tags": [],
                  "type": "dashboard"
                },
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "fiscalYearStartMonth": 0,
          "graphTooltip": 0,
          "links": [],
          "liveNow": true,
          "panels": [
            {
              "aliasColors": {},
              "bars": true,
              "dashLength": 10,
              "dashes": false,
              "datasource": {
                "type": "postgres",
                "uid": "PA942B37CCFAF5A81"
              },
              "fill": 1,
              "fillGradient": 0,
              "gridPos": {
                "h": 9,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "hiddenSeries": false,
              "id": 2,
              "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": false,
                "total": false,
                "values": false
              },
              "lines": false,
              "linewidth": 1,
              "nullPointMode": "connected",
              "options": {
                "alertThreshold": true
              },
              "percentage": false,
              "pluginVersion": "8.3.4",
              "pointradius": 2,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "spaceLength": 10,
              "stack": false,
              "steppedLine": false,
              "targets": [
                {
                  "datasource": {
                    "type": "postgres",
                    "uid": "PA942B37CCFAF5A81"
                  },
                  "format": "time_series",
                  "group": [],
                  "metricColumn": "none",
                  "rawQuery": true,
                  "rawSql": "SELECT\n  to_timestamp(created_at, 'YYYY-MM-DD HH24:MI:SS.US+00') AS \"time\",\n  AVG(words) AS \"value\",\n  language AS \"metric\"\nFROM word_count\nGROUP BY language\nORDER BY \"time\"\nLIMIT 10",
                  "refId": "A",
                  "select": [
                    [
                      {
                        "params": [
                          "count"
                        ],
                        "type": "column"
                      }
                    ]
                  ],
                  "table": "counts",
                  "timeColumn": "count",
                  "timeColumnType": "int4",
                  "where": [
                    {
                      "name": "$__unixEpochFilter",
                      "params": [],
                      "type": "macro"
                    }
                  ]
                }
              ],
              "thresholds": [],
              "timeRegions": [],
              "title": "Tweet Counts by Language",
              "tooltip": {
                "shared": false,
                "sort": 0,
                "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                "mode": "series",
                "show": true,
                "values": [
                  "current"
                ]
              },
              "yaxes": [
                {
                  "format": "short",
                  "logBase": 1,
                  "show": true
                },
                {
                  "format": "short",
                  "logBase": 1,
                  "show": true
                }
              ],
              "yaxis": {
                "align": false
              }
            }
          ],
          "refresh": "5s",
          "schemaVersion": 34,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-5m",
            "to": "now"
          },
          "timepicker": {
            "hidden": true,
            "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
            ],
            "time_options": [
              "5m",
              "15m",
              "1h",
              "6h",
              "12h",
              "24h",
              "2d",
              "7d",
              "30d"
            ]
          },
          "timezone": "",
          "title": "Counts",
          "uid": "JSr42WDWz",
          "version": 1,
          "weekStart": ""
        }